name: example-install-command
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          install-command: yarn --frozen-lockfile --silent
          working-directory: bluise/yarn
      - run: npm install node-sass --unsafe-perm=true --allow-root
      working-directory: bluise/yarn
